# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='source', max_length=7)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='ActionSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('controller', models.CharField(max_length=40, verbose_name='controller')),
                ('css_class', models.CharField(max_length=40, verbose_name='css class')),
                ('is_source', models.BooleanField(default=False, verbose_name='is source')),
                ('is_target', models.BooleanField(default=False, verbose_name='is target')),
            ],
            options={
                'verbose_name': 'connector',
            },
        ),
        migrations.CreateModel(
            name='FacebookConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('id_page', models.CharField(max_length=300, verbose_name='id page')),
                ('id_form', models.CharField(max_length=300, verbose_name='id form')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MySQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('host', models.CharField(max_length=40, verbose_name='host')),
                ('database', models.CharField(max_length=40, verbose_name='host')),
                ('port', models.CharField(max_length=5, verbose_name='port')),
                ('connection_user', models.CharField(max_length=40, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='host')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('action_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ActionSpecification')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='TargetSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('action_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ActionSpecification')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Connector'),
        ),
    ]
