import os

# Facebook
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET')


# Slack
SLACK_CLIENT_ID = os.environ.get('SLACK_CLIENT_ID')
SLACK_CLIENT_SECRET = os.environ.get('SLACK_CLIENT_SECRET')


# Google
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')


# Twitter
TWITTER_CLIENT_ID = os.environ.get('TWITTER_CLIENT_ID')
TWITTER_CLIENT_SECRET = os.environ.get('TWITTER_CLIENT_SECRET')


# SurveyMonkey
SURVEYMONKEY_CLIENT_ID = os.environ.get('SURVEYMONKEY_CLIENT_ID')
SURVEYMONKEY_CLIENT_SECRET = os.environ.get('SURVEYMONKEY_CLIENT_ID')


# Instagram
INSTAGRAM_CLIENT_ID = os.environ.get('INSTAGRAM_CLIENT_ID')
INSTAGRAM_CLIENT_SECRET = os.environ.get('INSTAGRAM_CLIENT_SECRET')


# SalesForce
SALESFORCE_CLIENT_ID = os.environ.get('SALESFORCE_CLIENT_ID')
SALESFORCE_CLIENT_SECRET = os.environ.get('SALESFORCE_CLIENT_SECRET')


# Hubspot
HUBSPOT_CLIENT_ID = os.environ.get('HUBSPOT_CLIENT_ID')
HUBSPOT_CLIENT_SECRET = os.environ.get('HUBSPOT_CLIENT_SECRET')


# Evernote
EVERNOTE_CONSUMER_KEY = os.environ.get('EVERNOTE_CONSUMER_KEY')
EVERNOTE_CONSUMER_SECRET = os.environ.get('EVERNOTE_CONSUMER_SECRET')


# Shopify
SHOPIFY_API_KEY = os.environ.get('SHOPIFY_API_KEY')
SHOPIFY_API_KEY_SECRET = os.environ.get('SHOPIFY_API_KEY_SECRET')


# Asana
ASANA_CLIENT_ID = os.environ.get('ASANA_CLIENT_ID')
ASANA_CLIENT_SECRET = os.environ.get('ASANA_CLIENT_SECRET')


# Mercadolibre
MERCADOLIBRE_CLIENT_ID = os.environ.get('MERCADOLIBRE_CLIENT_ID')
MERCADOLIBRE_CLIENT_SECRET = os.environ.get('MERCADOLIBRE_CLIENT_SECRET')


# Wunderlist
WUNDERLIST_CLIENT_ID = os.environ.get('WUNDERLIST_CLIENT_ID')
WUNDERLIST_CLIENT_SECRET = os.environ.get('WUNDERLIST_CLIENT_SECRET')

# GitLab
GITLAB_CLIENT_ID = os.environ.get('GITLAB_CLIENT_ID')
GITLAB_CLIENT_SECRET = os.environ.get('GITLAB_CLIENT_SECRET')

# Wunderlist
MAILCHIMP_CLIENT_ID = os.environ.get('MAILCHIMP_CLIENT_ID')
MAILCHIMP_CLIENT_SECRET = os.environ.get('MAILCHIMP_CLIENT_SECRET')
