# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicevalidity',
            old_name='user',
            new_name='user_id',
        ),
    ]
