# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180104_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevalidityhistory',
            name='comment',
            field=models.CharField(default='', max_length=150, verbose_name='operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicevalidity',
            name='current_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='current balance'),
        ),
        migrations.AlterField(
            model_name='servicevalidity',
            name='total_recharged',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='recharge amount'),
        ),
        migrations.AlterField(
            model_name='servicevalidityhistory',
            name='operation',
            field=models.CharField(choices=[('1', 'Recharge'), ('2', 'Revoke'), ('3', 'Consumed'), ('4', 'Bonus recharge'), ('5', 'Refunded'), ('6', 'Modify Fee')], max_length=3, verbose_name='operation'),
        ),
    ]
