# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180104_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevalidityhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicevalidityhistory',
            name='operation',
            field=models.SmallIntegerField(choices=[(1, 'Recharge'), (2, 'Revoke'), (3, 'Consumed'), (4, 'Bonus recharge'), (5, 'Refunded'), (6, 'Modify Fee')], default=0, verbose_name='operation'),
        ),
    ]
