# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('text', models.TextField(max_length=5000, verbose_name='pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('text', models.TextField(max_length=1000, verbose_name='pregunta')),
                ('image', models.ImageField(default=None, null=True, upload_to='experience/image', verbose_name='imagen')),
            ],
        ),
    ]
