# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='source', max_length=7)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='ActionSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_specification', to='gp.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('css_class', models.CharField(max_length=40, verbose_name='css class')),
                ('is_source', models.BooleanField(default=False, verbose_name='is source')),
                ('is_target', models.BooleanField(default=False, verbose_name='is target')),
            ],
            options={
                'verbose_name': 'connector',
            },
        ),
        migrations.CreateModel(
            name='FacebookConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('id_page', models.CharField(max_length=300, verbose_name='id page')),
                ('id_form', models.CharField(max_length=300, verbose_name='id form')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_facebook', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='GearMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map', to='gp.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='GearMapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=300, verbose_name='target name')),
                ('source_value', models.CharField(max_length=300, verbose_name='source value')),
                ('gear_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map_data', to='gp.GearMap')),
            ],
        ),
        migrations.CreateModel(
            name='MySQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('host', models.CharField(max_length=40, verbose_name='host')),
                ('database', models.CharField(max_length=40, verbose_name='database')),
                ('table', models.CharField(max_length=40, verbose_name='table')),
                ('port', models.CharField(max_length=5, verbose_name='port')),
                ('connection_user', models.CharField(max_length=40, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mysql', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gp.Action')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plug', to='gp.Connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlugSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('action_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.ActionSpecification')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_specification', to='gp.Plug')),
            ],
        ),
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('value', models.CharField(max_length=3000, verbose_name='value')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=50, verbose_name='object_id')),
                ('connection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stored_data', to='gp.Connection')),
            ],
        ),
        migrations.AddField(
            model_name='gear',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_plug', to='gp.Plug'),
        ),
        migrations.AddField(
            model_name='gear',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_plug', to='gp.Plug'),
        ),
        migrations.AddField(
            model_name='gear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='connector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gp.Connector'),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='gp.Connector'),
        ),
        migrations.AlterUniqueTogether(
            name='plugspecification',
            unique_together=set([('plug', 'action_specification')]),
        ),
        migrations.AlterUniqueTogether(
            name='gearmap',
            unique_together=set([('id', 'gear')]),
        ),
    ]
