# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 21:43
from __future__ import unicode_literals

import apps.gp.model_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='source', max_length=7)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='ActionSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_specification', to='gp.Action')),
            ],
        ),
        migrations.CreateModel(
            name='AsanaConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('token_expiration_timestamp', models.CharField(max_length=300, verbose_name='token expiration timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='BitbucketConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('css_class', models.CharField(blank=True, max_length=40, verbose_name='css class')),
                ('is_source', models.BooleanField(default=False, verbose_name='is source')),
                ('is_target', models.BooleanField(default=False, verbose_name='is target')),
                ('icon', models.ImageField(default=None, null=True, upload_to='connector/icon', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'connector',
            },
        ),
        migrations.CreateModel(
            name='ConnectorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Connector')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Category')),
            ],
            options={
                'db_table': 'gp_connector__category',
            },
        ),
        migrations.CreateModel(
            name='ControllerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, default='', max_length=30)),
                ('process', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('f', 'Failed'), ('s', 'Successful')], default='f', max_length=2)),
                ('controller', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvernoteConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_evernote', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLeadsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_facebookleads', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='GearMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_sent_stored_data_creation_date', models.DateTimeField(default=None, null=True, verbose_name='last sent storeddata creation date')),
                ('last_source_update', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('gear', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map', to='gp.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='GearMapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=300, verbose_name='target name')),
                ('source_value', models.CharField(max_length=300, verbose_name='source value')),
                ('gear_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map_data', to='gp.GearMap')),
            ],
        ),
        migrations.CreateModel(
            name='GetResponseConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_getresponse', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googlecalendar', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleContactsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googlecontacts', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleFormsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googleforms', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePushWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=200, verbose_name='channel_id')),
                ('resource_id', models.CharField(max_length=200, verbose_name='resource_id')),
                ('expiration', models.CharField(max_length=200, verbose_name='expiration')),
                ('raw_expiration', models.CharField(max_length=200, verbose_name='raw_expiration')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_push_webhook', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleSpreadSheetsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googlespreadsheets', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='HubSpotConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='token')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_hubspotcrm', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_instagram', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_jira', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MagentoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_magento', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MailChimpConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=200, verbose_name='user')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mailchimp', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MandrillConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mandrill', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MercadoLibreConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('site', models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brazil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Ecuador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguay'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], max_length=3)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mercadolibre', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MSSQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('database', models.CharField(max_length=200, verbose_name='database')),
                ('table', models.CharField(max_length=200, verbose_name='table')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mssql', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MySQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('database', models.CharField(max_length=200, verbose_name='database')),
                ('table', models.CharField(max_length=200, verbose_name='table')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mysql', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('plug_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='source', max_length=7)),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('is_tested', models.BooleanField(default=False)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gp.Action')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plug', to='gp.Connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlugActionSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('action_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_specification', to='gp.ActionSpecification')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_action_specification', to='gp.Plug')),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('database', models.CharField(max_length=200, verbose_name='database')),
                ('table', models.CharField(max_length=200, verbose_name='table')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_postgresql', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_salesforce', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_shopify', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SlackConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_slack', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SMSConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_sms', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SMTPConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('port', models.CharField(max_length=200, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_smtp', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('value', models.CharField(blank=True, default='', max_length=3000, verbose_name='value')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=150, null=True, verbose_name='object_id')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_data', to='gp.Connection')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_data', to='gp.Plug')),
            ],
        ),
        migrations.CreateModel(
            name='SugarCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('connection_user', models.CharField(max_length=200, verbose_name='user')),
                ('connection_password', models.CharField(max_length=200, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_sugarcrm', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyMonkeyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_surveymonkey', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('token_secret', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_twitter', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='webhook name')),
                ('url', models.URLField(verbose_name='url')),
                ('generated_id', models.CharField(max_length=200, verbose_name='generated id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('expiration', models.CharField(default=None, max_length=200, null=True, verbose_name='expiration')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='gp.Plug')),
            ],
        ),
        migrations.CreateModel(
            name='WunderListConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_wunderlist', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_youtube', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='ZohoCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_zohocrm', to='gp.Connection')),
            ],
        ),
        migrations.AddField(
            model_name='gearmap',
            name='last_sent_stored_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_map', to='gp.StoredData'),
        ),
        migrations.AddField(
            model_name='gear',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_source', to='gp.Plug'),
        ),
        migrations.AddField(
            model_name='gear',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_target', to='gp.Plug'),
        ),
        migrations.AddField(
            model_name='gear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connector',
            name='category',
            field=models.ManyToManyField(through='gp.ConnectorCategory', to='gp.Category'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gp.Connector'),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitbucketconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_bitbucket', to='gp.Connection'),
        ),
        migrations.AddField(
            model_name='asanaconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_asana', to='gp.Connection'),
        ),
        migrations.AddField(
            model_name='action',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='gp.Connector'),
        ),
        migrations.AlterUniqueTogether(
            name='plugactionspecification',
            unique_together=set([('plug', 'action_specification')]),
        ),
        migrations.AlterUniqueTogether(
            name='gearmap',
            unique_together=set([('id', 'gear')]),
        ),
    ]
