# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:17
from __future__ import unicode_literals

import apps.gp.model_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaignConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('connection_access_key', models.CharField(max_length=100, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_activecampaign', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GearGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitLabConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_gitlab', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_gmail', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='VtigerConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_access_key', models.CharField(max_length=40, verbose_name='password')),
                ('token', models.CharField(blank=True, max_length=100, null=True, verbose_name='token')),
                ('url', models.URLField(verbose_name='url')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_vtiger', to='gp.Connection')),
            ],
        ),
        migrations.RenameField(
            model_name='mailchimpconnection',
            old_name='connection_user',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='gearmap',
            name='last_sent_stored_data_creation_date',
        ),
        migrations.RemoveField(
            model_name='mailchimpconnection',
            name='api_key',
        ),
        migrations.AddField(
            model_name='gearmap',
            name='last_source_order_by_field_value',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='shopifyconnection',
            name='shop_url',
            field=models.CharField(default='', max_length=300, verbose_name='shop_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhook',
            name='plug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='gp.Plug'),
        ),
        migrations.AddField(
            model_name='gear',
            name='gear_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_group', to='gp.GearGroup'),
        ),
    ]
