# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearmap',
            name='gear',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map', to='gp.Gear'),
        ),
        migrations.AlterField(
            model_name='gearmapdata',
            name='gear_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_map_data', to='gp.GearMap'),
        ),
    ]
