# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibreconnection',
            name='user_id',
            field=models.CharField(default='', max_length=200, verbose_name='user_id'),
            preserve_default=False,
        ),
    ]
