# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:29
from __future__ import unicode_literals

import apps.gp.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_gitlab', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_gmail', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='VtigerConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_access_key', models.CharField(max_length=40, verbose_name='password')),
                ('token', models.CharField(blank=True, max_length=100, null=True, verbose_name='token')),
                ('url', models.URLField(verbose_name='url')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_vtiger', to='gp.Connection')),
            ],
        ),
        migrations.AddField(
            model_name='shopifyconnection',
            name='shop_url',
            field=models.CharField(default='', max_length=300, verbose_name='shop_url'),
            preserve_default=False,
        ),
    ]
