# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 23:33
from __future__ import unicode_literals

import apps.gp.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_instagramconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_youtube', to='gp.Connection')),
            ],
        ),
    ]
