# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20160816_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('value', models.CharField(max_length=3000, verbose_name='value')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=50, verbose_name='object_id')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulled_data', to='gp.Plug')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='gp.Connector'),
        ),
        migrations.AlterField(
            model_name='actionspecification',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_specification', to='gp.Action'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plugspecification',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_specification', to='gp.Plug'),
        ),
        migrations.AlterUniqueTogether(
            name='plugspecification',
            unique_together=set([('plug', 'action_specification')]),
        ),
        migrations.AlterUniqueTogether(
            name='storeddata',
            unique_together=set([('plug', 'object_id')]),
        ),
    ]
