# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20160825_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearmap',
            name='last_sent_stored_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gear_map', to='gp.StoredData'),
        ),
    ]
