# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_mercadolibreconnection_user_id'),
        ('gp', '0002_auto_20170830_1435'),
    ]

    operations = [
    ]
