# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20170905_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='gear_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear', to='gp.GearGroup'),
        ),
    ]
