# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20160907_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugarCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('url', models.CharField(max_length=40, verbose_name='host')),
                ('connection_user', models.CharField(max_length=40, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_sugarcrm', to='gp.Connection')),
            ],
        ),
    ]
