# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_salesforceconnection_shopifyconnection_smtpconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='webhook name')),
                ('url', models.URLField(verbose_name='url')),
                ('generated_id', models.CharField(max_length=200, verbose_name='generated id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('expiration', models.CharField(max_length=200, verbose_name='expiration')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='gp.Plug')),
            ],
        ),
    ]
