# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_merge_20170830_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecampaignconnection',
            name='connection',
        ),
        migrations.DeleteModel(
            name='ActiveCampaignConnection',
        ),
    ]
