# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_shopify'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopify',
            new_name='ShopifyConnection',
        ),
    ]
