# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_auto_20160909_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugarcrmconnection',
            name='module',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='sugarcrmconnection',
            name='connection_password',
            field=models.CharField(max_length=200, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='sugarcrmconnection',
            name='connection_user',
            field=models.CharField(max_length=200, verbose_name='user'),
        ),
    ]
