# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_geargroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearmap',
            name='last_sent_stored_data_creation_date',
        ),
        migrations.AddField(
            model_name='gearmap',
            name='last_source_order_by_field_value',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='gear_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear', to='gp.GearGroup'),
        ),
    ]
