# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_auto_20170921_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfusionSoftConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('token_expiration_time', models.CharField(max_length=300, verbose_name='token expiration time')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_infusionsoft', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='activecampaignconnection',
            name='connection_access_key',
            field=models.CharField(max_length=100, verbose_name='access key'),
        ),
    ]
