# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlugActionSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('action_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_specification', to='gp.ActionSpecification')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug', to='gp.Plug')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plugspecification',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plugspecification',
            name='action_specification',
        ),
        migrations.RemoveField(
            model_name='plugspecification',
            name='plug',
        ),
        migrations.DeleteModel(
            name='PlugSpecification',
        ),
        migrations.AlterUniqueTogether(
            name='plugactionspecification',
            unique_together=set([('plug', 'action_specification')]),
        ),
    ]
