# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20170904_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='plug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='gp.Plug'),
        ),
    ]
