# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20170905_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('user_id', models.CharField(max_length=200, verbose_name='name')),
                ('user_name', models.CharField(max_length=200, verbose_name='name')),
                ('plug_id', models.CharField(max_length=200, verbose_name='name')),
                ('specifications', models.CharField(max_length=300, verbose_name='token')),
                ('data', models.CharField(max_length=300, verbose_name='token')),
            ],
        ),
    ]
