# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20160909_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeddata',
            name='value',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='value'),
        ),
    ]
