# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20170925_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_id', models.CharField(max_length=25, verbose_name='gear_id')),
                ('plug_id', models.CharField(max_length=25, verbose_name='plug_id')),
                ('connection', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('raw', models.CharField(max_length=25000)),
                ('identifier', models.CharField(max_length=500, verbose_name='identifier')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Connector')),
            ],
        ),
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_id', models.CharField(max_length=25, verbose_name='gear_id')),
                ('plug_id', models.CharField(max_length=25, verbose_name='plug_id')),
                ('connection', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=25000)),
                ('response', models.CharField(max_length=25000)),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('identifier', models.CharField(max_length=500, verbose_name='identifier')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Connector')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFormConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=400, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_typeform', to='gp.Connection')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoryCount',
        ),
        migrations.RemoveField(
            model_name='vtigerconnection',
            name='token',
        ),
        migrations.AlterField(
            model_name='vtigerconnection',
            name='connection_access_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='access key'),
        ),
    ]
