# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20170901_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailchimpconnection',
            old_name='connection_user',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='mailchimpconnection',
            name='api_key',
        ),
    ]
