# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='count',
            name='data',
            field=models.CharField(max_length=300, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='count',
            name='plug_id',
            field=models.CharField(max_length=200, verbose_name='plug_id'),
        ),
        migrations.AlterField(
            model_name='count',
            name='specifications',
            field=models.CharField(max_length=300, verbose_name='specifications'),
        ),
        migrations.AlterField(
            model_name='count',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='count',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='user_name'),
        ),
    ]
