# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_hubspotcrmconnection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HubSpotCRMConnection',
            new_name='HubSpotConnection',
        ),
    ]
