# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_auto_20171004_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadhistory',
            name='connector',
        ),
        migrations.RemoveField(
            model_name='sendhistory',
            name='connector',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='icon',
        ),
        migrations.AddField(
            model_name='connector',
            name='connection_help_text',
            field=models.CharField(default='', max_length=3000, verbose_name='connection help text'),
        ),
        migrations.AddField(
            model_name='connector',
            name='icon15',
            field=models.ImageField(default=None, null=True, upload_to='connector/icon', verbose_name='icon 15px'),
        ),
        migrations.AddField(
            model_name='connector',
            name='icon73',
            field=models.ImageField(default=None, null=True, upload_to='connector/icon', verbose_name='icon 73px'),
        ),
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
        migrations.DeleteModel(
            name='SendHistory',
        ),
    ]
