# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_auto_20170926_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='identifier',
            field=models.CharField(default='', max_length=500, verbose_name='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='raw',
            field=models.CharField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='saved_data',
            field=models.CharField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='connection',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='data',
            field=models.CharField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='identifier',
            field=models.CharField(max_length=500, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='response',
            field=models.CharField(max_length=25000),
        ),
    ]
