# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_auto_20171004_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadhistory',
            name='connector',
        ),
        migrations.RemoveField(
            model_name='sendhistory',
            name='connector',
        ),
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
        migrations.DeleteModel(
            name='SendHistory',
        ),
    ]
