# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20171017_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='css_class',
        ),
        migrations.AddField(
            model_name='connector',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='connector',
            name='short_description',
            field=models.TextField(default='', max_length=256, verbose_name='short description'),
        ),
    ]
