# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp', '0007_auto_20171120_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api_key')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('domain', models.CharField(max_length=200, verbose_name='domain')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_agilecrm', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='avatar/default.jpeg', upload_to='avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='subscription', max_length=500)),
                ('description', models.CharField(default='description of subscription', max_length=500)),
                ('user', models.ManyToManyField(through='gp.Subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='smtpconnection',
            name='connection_password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_list', to='gp.SubscriptionsList'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
