# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20170928_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadhistory',
            name='saved_data',
        ),
    ]
