# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20170706_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandrillConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection_user', models.CharField(max_length=200, verbose_name='user')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mandrill', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='gear',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_source', to='gp.Plug'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_target', to='gp.Plug'),
        ),
        migrations.AlterField(
            model_name='plugactionspecification',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_action_specification', to='gp.Plug'),
        ),
    ]
