# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20170906_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='action'),
            preserve_default=False,
        ),
    ]
