# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_gearmap_last_sent_stored_data_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimpConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('connection_user', models.CharField(max_length=200, verbose_name='user')),
                ('connection_password', models.CharField(max_length=200, verbose_name='password')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
            ],
        ),
        migrations.RemoveField(
            model_name='sugarcrmconnection',
            name='module',
        ),
        migrations.AddField(
            model_name='connection',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='mailchimpconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mailchimp', to='gp.Connection'),
        ),
    ]
