# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20171025_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActEssentialsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=400, verbose_name='API Key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_actessentials', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='BatchbookConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('account_name', models.CharField(max_length=200, verbose_name='account_name')),
                ('access_key', models.CharField(max_length=100, verbose_name='access key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_batchbook', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GearFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=256, verbose_name='field name')),
                ('option', models.IntegerField(choices=[(1, 'CONTAINS'), (2, 'DOES_NOT_CONTAIN'), (3, 'EQUALS'), (4, 'DOES_NOT_EQUAL'), (5, 'IS_EMPTY'), (6, 'IS_NOT_EMPTY'), (7, 'STARTS_WITH'), (8, 'DOES_NOT_START_WITH'), (9, 'ENDS_WITH'), (10, 'DOES_NOT_END_WITH'), (11, 'LESS_THAN'), (12, 'GREATER_THAN'), (13, 'LENGTH_EQUALS'), (14, 'LENGTH_IS_LESS_THAN'), (15, 'LENGTH_IS_GREATER_THAN')], verbose_name='option')),
                ('comparison_data', models.CharField(max_length=100, verbose_name='comparison data')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_filter', to='gp.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='OdooCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('database', models.CharField(max_length=200, verbose_name='database')),
                ('connection_user', models.CharField(max_length=200, verbose_name='user')),
                ('connection_password', models.CharField(max_length=200, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_odoocrm', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_webhook', to='gp.Connection')),
            ],
        ),
        migrations.RemoveField(
            model_name='googlepushwebhook',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='typeformconnection',
            name='api_key',
        ),
        migrations.AddField(
            model_name='gearmap',
            name='version',
            field=models.SmallIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='gearmapdata',
            name='version',
            field=models.SmallIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='typeformconnection',
            name='token',
            field=models.CharField(default='', max_length=400, verbose_name='token'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GooglePushWebhook',
        ),
    ]
