# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_count_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='data',
            field=models.CharField(max_length=2000, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='count',
            name='specifications',
            field=models.CharField(max_length=1000, verbose_name='specifications'),
        ),
    ]
