# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20161004_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailchimpconnection',
            name='connection_password',
        ),
        migrations.AlterField(
            model_name='gear',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_gear', to='gp.Plug'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_gear', to='gp.Plug'),
        ),
        migrations.AlterField(
            model_name='gearmap',
            name='last_sent_stored_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_map', to='gp.StoredData'),
        ),
    ]
