# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20171115_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileCRMConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api_key')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('domain', models.CharField(max_length=200, verbose_name='domain')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_agilecrm', to='gp.Connection')),
            ],
        ),
    ]
