# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20170713_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforceconnection',
            name='connection_password',
        ),
        migrations.RemoveField(
            model_name='salesforceconnection',
            name='connection_user',
        ),
        migrations.AlterField(
            model_name='salesforceconnection',
            name='token',
            field=models.CharField(max_length=300, verbose_name='token'),
        ),
    ]
