# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20171213_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Colombia', max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Colombia', max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='Colombia', max_length=50, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='hubspotconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_hubspot', to='gp.Connection'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpeg', upload_to='avatar/', verbose_name='avatar'),
        ),
    ]
