# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20171211_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconnection',
            name='connection_password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
    ]
