# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_auto_20170718_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandrillconnection',
            name='connection_user',
        ),
    ]
