# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0009_auto_20171227_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='state'),
        ),
    ]
