# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_auto_20170906_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=200, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=200, verbose_name='user_name')),
                ('plug_id_input', models.CharField(max_length=200, verbose_name='plug_id')),
                ('action_input', models.CharField(max_length=200, verbose_name='action_input')),
                ('specifications_input', models.CharField(max_length=1000, verbose_name='specifications_input')),
                ('data_input', models.CharField(max_length=2000, verbose_name='data')),
                ('plug_id_output', models.CharField(max_length=200, verbose_name='plug_id_output')),
                ('action_output', models.CharField(max_length=200, verbose_name='action_output')),
                ('specifications_output', models.CharField(max_length=1000, verbose_name='specifications_output')),
                ('data_output', models.CharField(max_length=2000, verbose_name='data_output')),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
