# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_remove_mailchimpconnection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugspecification',
            name='extra',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='extra'),
        ),
    ]
