# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_evernoteconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('token_expiration_timestamp', models.CharField(max_length=300, verbose_name='token expiration timestamp')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_asana', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MagentoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_magento', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MandrillConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mandrill', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MercadoLibreConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('site', models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brazil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Ecuador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguay'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], max_length=3)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mercadolibre', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='webhook',
            name='expiration',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='expiration'),
        ),
    ]
