# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_evernoteconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('token_expiration_timestamp', models.CharField(max_length=300, verbose_name='token expiration timestamp')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_asana', to='gp.Connection')),
            ],
        ),
    ]
