# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_asanaconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaconnection',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
    ]
