# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_plugspecification_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugspecification',
            name='extra',
        ),
    ]
