# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_auto_20170802_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facebookleadsconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_facebookleads', to='gp.Connection'),
        ),
    ]
