# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 17:27
from __future__ import unicode_literals

import apps.gp.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_auto_20170802_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_gmail', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='facebookleadsconnection',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_facebookleads', to='gp.Connection'),
        ),
    ]
