# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_mercadolibreconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='refresh token')),
                ('token_expiration_timestamp', models.CharField(max_length=300, verbose_name='token expiration timestamp')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_asana', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='MandrillConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mandrill', to='gp.Connection')),
            ],
        ),
        migrations.AddField(
            model_name='mercadolibreconnection',
            name='site',
            field=models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brazil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Ecuador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguay'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], default='MLA', max_length=3),
            preserve_default=False,
        ),
    ]
