# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0012_remove_plugspecification_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, default='', max_length=30)),
                ('process', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('f', 'Failed'), ('s', 'Successful')], default='f', max_length=2)),
                ('controller', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
