# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0013_controllerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearmap',
            name='last_source_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
