# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0014_controllerlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControllerLog',
        ),
        migrations.AddField(
            model_name='generallog',
            name='module',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='generallog',
            name='process',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
