# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0018_auto_20161230_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSSQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('database', models.CharField(max_length=200, verbose_name='database')),
                ('table', models.CharField(max_length=200, verbose_name='table')),
                ('port', models.CharField(max_length=7, verbose_name='port')),
                ('connection_user', models.CharField(max_length=60, verbose_name='user')),
                ('connection_password', models.CharField(max_length=40, verbose_name='password')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_mssql', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='connector',
            name='icon',
            field=models.ImageField(default=None, null=True, upload_to='connector/icon', verbose_name='icon'),
        ),
    ]
