# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0021_jiraconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
    ]
