# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0022_googlecontactsconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeddata',
            name='object_id',
            field=models.CharField(max_length=150, null=True, verbose_name='object_id'),
        ),
    ]
