# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0023_googleformsconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('token_secret', models.CharField(max_length=300, verbose_name='token')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_twitter', to='gp.Connection')),
            ],
        ),
    ]
