# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0023_googleformsconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetResponseConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_getresponse', to='gp.Connection')),
            ],
        ),
    ]
