# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 19:06
from __future__ import unicode_literals

import apps.gp.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0024_twitterconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetResponseConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('api_key', models.CharField(max_length=200, verbose_name='api key')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_getresponse', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleContactsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googlecontacts', to='gp.Connection')),
            ],
        ),
        migrations.AlterField(
            model_name='storeddata',
            name='object_id',
            field=models.CharField(max_length=150, null=True, verbose_name='object_id'),
        ),
    ]
