# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0025_googlecalendarconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePushWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=200, verbose_name='channel_id')),
                ('resource_id', models.CharField(max_length=200, verbose_name='resource_id')),
                ('expiration', models.CharField(max_length=200, verbose_name='expiration')),
                ('raw_expiration', models.CharField(max_length=200, verbose_name='raw_expiration')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_push_webhook', to='gp.Connection')),
            ],
        ),
    ]
