# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 19:33
from __future__ import unicode_literals

import apps.gp.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0026_category_connectiondata_geardata_plugdata_surveymonkeyconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Connector')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Category')),
            ],
            options={
                'db_table': 'gp_connector__category',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('credentials_json', apps.gp.model_fields.JSONField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_googlecalendar', to='gp.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePushWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=200, verbose_name='channel_id')),
                ('resource_id', models.CharField(max_length=200, verbose_name='resource_id')),
                ('expiration', models.CharField(max_length=200, verbose_name='expiration')),
                ('raw_expiration', models.CharField(max_length=200, verbose_name='raw_expiration')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_push_webhook', to='gp.Connection')),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectionData',
        ),
        migrations.DeleteModel(
            name='GearData',
        ),
        migrations.DeleteModel(
            name='PlugData',
        ),
        migrations.AddField(
            model_name='connector',
            name='category',
            field=models.ManyToManyField(through='gp.ConnectorCategory', to='gp.Category'),
        ),
    ]
