# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0026_category_connectiondata_geardata_plugdata_surveymonkeyconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Connector')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Category')),
            ],
            options={
                'db_table': 'gp_connector__category',
            },
        ),
        migrations.DeleteModel(
            name='ConnectionData',
        ),
        migrations.DeleteModel(
            name='GearData',
        ),
        migrations.DeleteModel(
            name='PlugData',
        ),
        migrations.AddField(
            model_name='connector',
            name='category',
            field=models.ManyToManyField(through='gp.ConnectorCategory', to='gp.Category'),
        ),
    ]
