# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=25, verbose_name='connector_id')),
                ('gear_id', models.CharField(max_length=25, verbose_name='gear_id')),
                ('plug_id', models.CharField(max_length=25, verbose_name='plug_id')),
                ('connection', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('raw', models.CharField(max_length=25000)),
                ('identifier', models.CharField(max_length=500, verbose_name='identifier')),
            ],
            options={
                'db_table': 'gp_downloadhistory',
            },
        ),
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=25, verbose_name='connector_id')),
                ('gear_id', models.CharField(max_length=25, verbose_name='gear_id')),
                ('plug_id', models.CharField(max_length=25, verbose_name='plug_id')),
                ('connection', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=25000)),
                ('response', models.CharField(max_length=25000)),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('identifier', models.CharField(max_length=500, verbose_name='identifier')),
            ],
            options={
                'db_table': 'gp_sendhistory',
            },
        ),
    ]
