# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='version',
            field=models.CharField(default=1, max_length=500, verbose_name='version'),
        ),
    ]
