# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='tries',
            field=models.IntegerField(default=1),
        ),
    ]
