# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='version',
            field=models.CharField(default=1, max_length=500, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='sent',
            field=models.SmallIntegerField(choices=[(0, 'Failed'), (1, 'Success'), (2, 'Filtered')], default=0, verbose_name='sent'),
        ),
    ]
