# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_sendhistory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhistory',
            name='sent',
            field=models.SmallIntegerField(choices=[(0, 'Failed'), (1, 'Success'), (2, 'Filtered')], default=0, verbose_name='sent'),
        ),
    ]
